#!/bin/bash

# Called by "git push" after it has checked the remote status, but before anything has
# been pushed. If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>


BAR="###########"

# echo -e "\033[0;34m${BAR} Running tests... ${BAR}\033[0m"

# npm run coverage
# if [[ "$?" -ne 0 ]]; then
#   echo -e "\033[0;31m${BAR} FAILED! Please pass tests before pushing. ${BAR}\033[0m"
#   exit 1
# else
#   echo -e "\033[0;32m${BAR} PASSED! ${BAR}\033[0m"
# fi

echo -e "\033[0;34m${BAR} Checking code style... ${BAR}\033[0m"

npm run lint
if [[ "$?" -ne 0 ]]; then
  echo -e "\033[0;31m${BAR} FAILED! Please fix code style before pushing. ${BAR}\033[0m"
  exit 1
else
  echo -e "\033[0;32m${BAR} PASSED! ${BAR}\033[0m"
fi

echo -e "\033[0;34m${BAR} Checking typescript... ${BAR}\033[0m"

which npx &> /dev/null
if [[ "$?" -ne 0 ]]; then
  echo -e "\033[0;34m${BAR} command \"npx\" not found. Ommiting... ${BAR}\033[0m"
  exit 0
fi

npx tsc
if [[ "$?" -ne 0 ]]; then
  echo -e "\033[0;31m${BAR} FAILED! Please fix typescript errors before pushing. ${BAR}\033[0m"
  exit 1
else
  echo -e "\033[0;32m${BAR} PASSED! ${BAR}\033[0m"
fi

exit 0